'use server';

/**
 * @fileOverview AI agent that generates structured meeting minutes from card updates and discussions.
 *
 * - generateMeetingMinutes - A function to generate meeting minutes.
 * - MeetingMinutesInput - The input type for the generateMeetingMinutes function.
 * - MeetingMinutesOutput - The return type for the generateMeetingMinutes function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MeetingMinutesInputSchema = z.object({
  cardUpdates: z
    .string()
    .describe('A summary of updates from cards discussed during the meeting.'),
  discussionSummary: z
    .string()
    .describe('A summary of the discussions that occurred during the meeting.'),
});
export type MeetingMinutesInput = z.infer<typeof MeetingMinutesInputSchema>;

const MeetingMinutesOutputSchema = z.object({
  minutes: z.string().describe('Structured meeting minutes generated by the AI.'),
});
export type MeetingMinutesOutput = z.infer<typeof MeetingMinutesOutputSchema>;

export async function generateMeetingMinutes(
  input: MeetingMinutesInput
): Promise<MeetingMinutesOutput> {
  return generateMeetingMinutesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'meetingMinutesPrompt',
  input: {schema: MeetingMinutesInputSchema},
  output: {schema: MeetingMinutesOutputSchema},
  prompt: `You are an AI assistant specializing in generating structured meeting minutes.
  Based on the card updates and discussion summaries provided, create detailed and well-organized meeting minutes.

  Card Updates: {{{cardUpdates}}}
  Discussion Summary: {{{discussionSummary}}}

  Meeting Minutes:
`,
});

const generateMeetingMinutesFlow = ai.defineFlow(
  {
    name: 'generateMeetingMinutesFlow',
    inputSchema: MeetingMinutesInputSchema,
    outputSchema: MeetingMinutesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
